//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        public int OGRTID { get; set; }
        public string OGRTAD { get; set; }
        public string OGRTSOYAD { get; set; }
        public string OGRTTC { get; set; }
        public string OGRTTEL { get; set; }
        public string OGRTMAIL { get; set; }
        public string OGRTADRES { get; set; }
        public string OGRTBRANS { get; set; }
    
        public virtual OgrtAyarlar OgrtAyarlar { get; set; }
    }
}
