//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrtAyarlar
    {
        public int AYARLAROGRTID { get; set; }
        public string OGRTSIFRE { get; set; }
    
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
